name: ubuntu

services:
  ssh:
    image: ubuntu-ssh:latest
    container_name: ssh-a
    build:
      context: .
      dockerfile: Dockerfile
    pull_policy: build
    ports:
      - 2221:22
  sshb:
    container_name: ssh-b
    image: ubuntu-ssh:latest
    pull_policy: build
    ports:
      - 2222:22
    depends_on:
      - ssh
  sshc:
    container_name: ssh-c
    image: ubuntu-ssh:latest
    pull_policy: build
    ports:
      - 2223:22
    depends_on:
      - ssh
  sshd:
    container_name: ssh-d
    image: ubuntu-ssh:latest
    pull_policy: build
    ports:
      - 2224:22
    depends_on:
      - ssh
